### ISSUE TITLE
I want to get the original image file of the visualization and compare it in the paper, thank you!

### ISSUE THREAD

**Issue by ncp-nice** [Minimel/MedSAMWeakFewShotPromptAutomation#3]
![{11696A95-1077-4D97-A4DB-07027CECD1AA}](https://github.com/user-attachments/assets/1d27adfd-ce90-41ec-9d4f-b2b4ae188d08)
I want to get the original image file of the visualization and compare it in the paper, thank you!If you can, please send me an email 1577469388@qq.com to congratulate you on the success of your research！

**Comment by Minimel** [comment]
Hi, this figure was obtained by getting the individual visualization results for each method, so I cannot provide a code for generating the overall figure. However, you can train the different models separately and generate the segmentation masks on the test data. 
In the paper, predictions for patient 243 of the HC18 dataset and slice 10 of patient 129 from the ACDC dataset are shown, for an initialization seed set to 0. If you have other questions, you can email me at melanie.gaillochet.1@ens.etsmtl.ca.
